wget https://www.dropbox.com/s/ppyp3izcb1us8hb/training_sample.csv?dl=1
mv training_sample.csv?dl=1 Data/training_sample.csv
wget https://www.dropbox.com/s/c4n74myrw5ryd02/dataset_test.csv?dl=1
mv dataset_test.csv?dl=1 Data/dataset_test.csv
wget https://www.dropbox.com/s/rhy90y1t75cst2c/full_training_data.csv?dl=1
mv full_training_data.csv?dl=1 Data/full_training_data.csv
wget https://www.dropbox.com/s/ppyp3izcb1us8hb/training_sample.csv?dl=1
mv training_sample.csv?dl=1 Data/training_sample.csv
wget https://www.dropbox.com/s/qlaqvctryi9k2nc/dataset_training.csv?dl=1
mv dataset_training.csv?dl=1 Data/dataset_training.csv
